server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-product-service
          uri: http://localhost:8082
          predicates:
            - Path=/v1/tax/**
