server:
  port: 8082

spring:
  application:
    name: user-product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true
  kafka:
    topic:
      name: service-log-topic
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
