version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"